version: '3'

services:
  cli:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    tty: true
    volumes:
      - ./src:/contact_bot_src
    environment:
      - CI
      - SHEET_ACCESS_TOKEN
      - SHEET_EXPIRY
      - SHEET_TOKEN_TYPE
      - SHEET_REFRESH_TOKEN
      - SLACK_WEBHOOK_URL
      - SHEET_CREDENTIAL
      - SPREAD_SHEET_ID
