name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: docker
      run: docker-compose build

    - name: Get dependencies
      run: |
        docker-compose run cli go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: docker-compose run cli go build -v .

    - name: Test
      run: docker-compose run cli go test -v ./...
